### ISSUE TITLE
issues with scikit-image loading in python despite no apparent issues at installation using conda-forge 

### ISSUE THREAD

**Issue by mirelatulbure** [conda-forge/scikit-image-feedstock#51]
Issue:

Hi, I'm trying to use the following in python:
`from skimage.measure import regionprops`

in addition to other modules, listed below:

```
import glob
import numpy as np
from osgeo import gdal
from igraph import *
import scipy.ndimage as ndimage
from scipy import ndimage as nd
import os
import itertools
import pandas as pd
import datetime
import optparse
```

I have created a new environment using Conda, as follows:

```
conda create -y -c conda-forge -n mirela_env_py373 python=3.7.3 gdal=3.0.1 scipy=1.3.0 numpy=1.16.4 pandas=0.24.2 igraph=0.7.1 python-igraph=0.7.1 scikit-image=0.15.0

conda activate mirela_env_py373
```

While all other modules I listed above load  properly in python, 
I get the following errors when trying to import skimage in python:

```
>>> from skimage.measure import regionprops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/util/__init__.py", line 12, in <module>
    from ._montage import montage
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/util/_montage.py", line 2, in <module>
    from .. import exposure
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/exposure/__init__.py", line 1, in <module>
    from .exposure import histogram, equalize_hist, \
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/exposure/exposure.py", line 3, in <module>
    from ..color import rgb2gray
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/color/__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/color/colorconv.py", line 55, in <module>
    from scipy import linalg
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: //anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so
  Reason: image not found

>>> import skimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/data/__init__.py", line 13, in <module>
    from ..io import imread, use_plugin
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/io/__init__.py", line 11, in <module>
    from ._io import *
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/io/_io.py", line 4, in <module>
    from ..color import rgb2gray
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/color/__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/skimage/color/colorconv.py", line 55, in <module>
    from scipy import linalg
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(//anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: //anaconda3/envs/mirela_env_py373/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so
  Reason: image not found
>
```

```
Environment (<code>conda list</code>):
<# packages in environment at //anaconda3/envs/mirela_env_py373:
#
# Name                    Version                   Build  Channel
blas                      2.12                   openblas    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cfitsio                   3.470                h389770f_2    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.10.0           py37h01d97ff_0    conda-forge
dask-core                 2.4.0                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.1            py37h4b80d33_8    conda-forge
geos                      3.7.2                h6de7cb9_2    conda-forge
geotiff                   1.5.1                h2bcb450_3    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h0cbb7df_1103    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
igraph                    0.7.1             h02d7eb0_1007    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   3.0.1                h61e1f9c_8    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
liblapacke                3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             h1a02027_1003    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.5                 h756f0eb_1    conda-forge
libspatialite             4.3.0a            hd0a3780_1030    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
matplotlib-base           3.1.1            py37h3a684a6_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.4           py37h6b0580a_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                hdc36067_1    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pandas                    0.24.2           py37h86efe34_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pillow                    6.1.0            py37h75ffe9a_1    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               hd5eb092_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 h25afefd_1    conda-forge
proj4                     6.1.1                hca663eb_1    conda-forge
pycairo                   1.18.1           py37h650f75e_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-igraph             0.7.1.post7      py37h01d97ff_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pywavelets                1.0.3            py37h1e5eb4f_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
scikit-image              0.15.0           py37h86efe34_2    conda-forge
scipy                     1.3.0            py37h1a1e112_0  
setuptools                41.2.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hb7d70f7_1    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.6.2                h4f44bfb_1    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xerces-c                  3.2.2             hbda6038_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
>
```
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
<
     active environment : mirela_env_py373
    active env location : //anaconda3/envs/mirela_env_py373
            shell level : 2
       user config file : /Users/mgabrie3/.condarc
 populated config files : /Users/mgabrie3/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : //anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : //anaconda3/pkgs
                          /Users/mgabrie3/.conda/pkgs
       envs directories : //anaconda3/envs
                          /Users/mgabrie3/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
>

**Comment by hmaarrfk** [comment]
Your scipy install is from defaults. Is that desired? Can you remove the scipy pinning and let it install whatever it needs to from conda forge? We may have skipped that exact version

**Comment by mirelatulbure** [comment]
Thank you - that worked! I removed the spicy pinning using the below and it installed SciPy 1.3.1 with conda-forge:
conda create -y -c conda-forge -n mirela_env_py373 python=3.7.3 gdal=3.0.1 scipy numpy=1.16.4 pandas=0.24.2 igraph=0.7.1 python-igraph=0.7.1 scikit-image=0.15.0

**Comment by hmaarrfk** [comment]
Generally with conda forge, you want to avoid pinning so hard. Only pin at the very end, when it is time to release your software as a complete package.
